// ZIP-Export. Enthält nur tatsächlich erzeugte Dateien; fehlende werden in audit.md und audit.json erklärt.
// Dateinamen überschreiben nie Originaldateien eines Repositorys (z. B. README.suggested.md statt README.md).

import { strToU8, zipSync } from "fflate";
import type { AiPackageResult } from "../ai/generate";
import type { AuditResult, Language, RepoSnapshot, UserContext } from "../types";
import { renderAuditMarkdown, renderLaunchPlanMarkdown, renderMarketingDrafts, renderMonetizationMarkdown, renderReadmeSuggested, type ExportFileInfo } from "./markdown";

export const GENERATOR = { name: "RepoLaunch", version: "0.1.0" };

export const EXPORT_FILES = ["audit.json", "audit.md", "README.suggested.md", "launch-plan.md", "monetization-plan.md", "marketing-drafts.md"] as const;

function omittedReason(name: string, ai: AiPackageResult | null, lang: Language): string {
  const de = lang === "de";
  if (!ai) return de ? "Wird nur mit dem optionalen KI-Launch-Paket erzeugt, das nicht ausgeführt wurde." : "Only generated by the optional AI launch package, which was not run.";
  if (name === "README.suggested.md") return de ? "README-Entwurf wurde im KI-Auftrag nicht gewählt." : "README draft was not selected in the AI job.";
  return de ? "Kein passender Abschnitt im KI-Auftrag gewählt." : "No matching section selected in the AI job.";
}

/** Schnappschuss ohne Dateiinhalte für audit.json. */
export function snapshotSummary(s: RepoSnapshot) {
  return {
    source: s.source,
    fixtureName: s.fixtureName,
    fullName: s.fullName,
    htmlUrl: s.htmlUrl,
    defaultBranch: s.defaultBranch,
    commitSha: s.commitSha,
    analyzedAt: s.analyzedAt,
    meta: s.meta,
    display: s.display,
    tree: { entries: s.tree.entries.length, scannedDirs: s.tree.scannedDirs, truncated: s.tree.truncated },
    readme: s.readme.state === "present" ? { state: s.readme.state, path: s.readme.path, size: s.readme.size } : s.readme,
    files: Object.fromEntries(Object.entries(s.files).map(([k, v]) => [k, v.state === "present" ? { state: v.state, path: v.path, size: v.size } : v])),
    releases: s.releases,
    goodFirstIssues: s.goodFirstIssues,
    stats: s.stats,
    notes: s.notes,
  };
}

export interface ExportBundle {
  filename: string;
  zip: Uint8Array;
  files: ExportFileInfo[];
  contents: Record<string, string>;
}

export function buildExport(snapshot: RepoSnapshot, audit: AuditResult, user: UserContext, ai: AiPackageResult | null): ExportBundle {
  const lang = user.language;
  const generated: Record<string, string | null> = {
    "README.suggested.md": ai ? renderReadmeSuggested(ai, lang) : null,
    "launch-plan.md": renderLaunchPlanMarkdown(snapshot, audit, user, ai),
    "monetization-plan.md": renderMonetizationMarkdown(snapshot, audit, user, ai),
    "marketing-drafts.md": ai ? renderMarketingDrafts(snapshot, ai, lang) : null,
  };
  const files: ExportFileInfo[] = EXPORT_FILES.map((name) => {
    if (name === "audit.json" || name === "audit.md") return { name, included: true };
    return generated[name] ? { name, included: true } : { name, included: false, reason: omittedReason(name, ai, lang) };
  });

  const auditJson = JSON.stringify(
    {
      generator: GENERATOR,
      schemaVersion: 1,
      repository: snapshotSummary(snapshot),
      user,
      audit,
      ai: ai
        ? {
            provider: ai.provider,
            providerId: ai.providerId,
            model: ai.model,
            isTestAdapter: ai.isTestAdapter,
            createdAt: ai.createdAt,
            sections: ai.sections,
            output: ai.output,
            checks: ai.checks,
            cost: ai.cost,
            disclosure: ai.disclosure,
          }
        : null,
      export: { files },
    },
    null,
    2,
  );

  const contents: Record<string, string> = {
    "audit.json": auditJson,
    "audit.md": renderAuditMarkdown(snapshot, audit, user, files, ai),
  };
  for (const [name, text] of Object.entries(generated)) if (text) contents[name] = text;

  const folder = `repolaunch-${snapshot.owner}-${snapshot.repo}-${snapshot.commitSha.slice(0, 7)}`.replace(/[^A-Za-z0-9._-]/g, "_");
  const mtime = new Date(snapshot.analyzedAt);
  const entries: Record<string, [Uint8Array, { mtime: Date }]> = {};
  for (const name of EXPORT_FILES) {
    const text = contents[name];
    if (text !== undefined) entries[`${folder}/${name}`] = [strToU8(text), { mtime }];
  }
  return { filename: `${folder}.zip`, zip: zipSync(entries, { level: 6 }), files, contents };
}
